package org.bio.jobs;
import org.bio.model.Operateur;
import org.bio.report.*;
import org.ini4j.InvalidFileFormatException;

import com.mysql.jdbc.Statement;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
//============================================================================
//
//Copyright (c) 2006-2013, Talend Inc.
//
//This source code has been automatically generated by_Talend Open Studio for Data Integration
/// Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
import java.sql.ResultSet;
import java.sql.SQLException;






public class PasswordFetch  {


    public String getPassword(String login) throws SQLException, InvalidFileFormatException, FileNotFoundException, IOException {
    	
    	  Connection connection = null;
    	  String pswd = "password";
      	
      		  connection = DatabaseConnection.getConnectionSpago();
    	
      		
      			Statement stmt = (Statement) connection.createStatement();
				ResultSet rs = stmt.executeQuery("SELECT password FROM spagobi42.SBI_USER s where s.USER_ID = '"+login+"'");
				
				
				
				while ( rs.next() ) {
	                pswd = rs.getString("password");
	                System.out.println(pswd);
				
				
		
	  	
    
            
      	
}
      		return pswd;
    }
}
/************************************************************************************************
* 53121 characters generated by Talend Open Studio for Data Integration on the
* 11 juin 2014 11:03:21 CET
************************************************************************************************/
