package org.bio.model;

// Generated 19 mars 2014 17:02:06 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Categorie generated by hbm2java
 */
@Entity
@Table(name = "categorie")
public class Categorie implements java.io.Serializable {

	private int idcat;
	private String desigCat;
	private String description;
	//private Boolean verrouiller;
	//private Integer longueurSeq;
	//private String typeSeq;
	private Set<Horaires> horaireses = new HashSet<Horaires>(0);
	private Set<Historique> historiques = new HashSet<Historique>(0);

	
	public Categorie() {}
	public Categorie(int idcat) {this.idcat=idcat;}

	public Categorie(int idcat, String desigCat,String description,Set<Horaires> horaireses,
			Set<Historique> historiques) {
		this.idcat=idcat;
		this.desigCat = desigCat;
		//this.verrouiller = verrouiller;
		//this.longueurSeq = longueurSeq;
		//this.typeSeq = typeSeq;
		this.horaireses = horaireses;
		this.historiques = historiques;
		this.description=description;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "idcat", unique = true, nullable = false)
	public int getIdcat() {
		return this.idcat;
	}

	public void setIdcat(int idcat) {
		this.idcat = idcat;
	}

	@Column(name = "desigCat", length = 20)
	public String getDesigCat() {
		return this.desigCat;
	}

	public void setDesigCat(String desigCat) {
		this.desigCat = desigCat;
	}
	
	@Column(name = "description", length = 20)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	/*@Column(name = "verrouiller")
	public Boolean getVerrouiller() {
	return this.verrouiller;
	}

	public void setVerrouiller(Boolean verrouiller) {
		this.verrouiller = verrouiller;
	}

	@Column(name = "longueurSeq")
	public Integer getLongueurSeq() {
		return this.longueurSeq;
	}

	public void setLongueurSeq(Integer longueurSeq) {
		this.longueurSeq = longueurSeq;
	}

	@Column(name = "typeSeq", length = 20)
	public String getTypeSeq() {
		return this.typeSeq;
	}

	public void setTypeSeq(String typeSeq) {
		this.typeSeq = typeSeq;
	}*/

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "categorie")
	public Set<Horaires> getHoraireses() {
		return this.horaireses;
	}

	public void setHoraireses(Set<Horaires> horaireses) {
		this.horaireses = horaireses;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "categorie")
	public Set<Historique> getHistoriques() {
		return this.historiques;
	}

	public void setHistoriques(Set<Historique> historiques) {
		this.historiques = historiques;
	}

}
