package org.bio.model;

// Generated 19 mars 2014 17:02:06 by Hibernate Tools 4.0.0

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * Mvt generated by hbm2java
 */
@Entity
@Table(name = "mvt")
@Cache(usage=CacheConcurrencyStrategy.READ_WRITE)
public class Mvt implements java.io.Serializable {

	private MvtId id;
	private Terminaux terminaux;
	

	@Override
	public String toString() {
		return "Mvt [id=" + id + " moyen=" + moyen + ", mode=" + mode
				+ ", jourLogique=" + jourLogique + ", jour=" + jour
				+ ", heure=" + heure + "]";
	}

	private Personnel personnel;
	
	private String moyen;
	private String mode;
	private String etatp;
	private String etatr;
	private String bcketat;
private Integer position;
	private Date jourLogique;
	private Date jour;
	private Date heure;
	private Integer bckId;
	private String etaticon;
private String etat;
private List<Mvt> listmvt;
	public Mvt() {
		listmvt=new ArrayList<Mvt>();
	}

	public Mvt(MvtId id, Terminaux terminaux, Personnel personnel) {
		this.id = id;
		this.terminaux = terminaux;
		this.personnel = personnel;
	}

	public Mvt(MvtId id, Terminaux terminaux, Personnel personnel, Date jour,
			Date heure, String moyen, String mode, Date jourLogique, String etat) {
		this.id = id;
		this.terminaux = terminaux;
		this.personnel = personnel;
		this.etat=etat;
		this.moyen = moyen;
		this.mode = mode;
		this.jourLogique = jourLogique;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idper", column = @Column(name = "idper", nullable = false)),
			@AttributeOverride(name = "idmvt", column = @Column(name = "idmvt", nullable = false)),
			@AttributeOverride(name = "idter", column = @Column(name = "idter", nullable = false)) })
	public MvtId getId() {
		return this.id;
	}

	public void setId(MvtId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idter", nullable = false, insertable = false, updatable = false)
	public Terminaux getTerminaux() {
		return this.terminaux;
	}

	public void setTerminaux(Terminaux terminaux) {
		this.terminaux = terminaux;
	}
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idper", nullable = false, insertable = false, updatable = false)
	public Personnel getPersonnel() {
		return this.personnel;
	}

	public void setPersonnel(Personnel personnel) {
		this.personnel = personnel;
	}

	

	@Column(name = "moyen",length = 30)
	public String getMoyen() {
		return this.moyen;
	}

	public void setMoyen(String moyen) {
		this.moyen = moyen;
	}

	@Column(name = "mode", length = 30)
	public String getMode() {
		return this.mode;
	}

	public void setMode(String mode) {
		this.mode = mode;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "jourLogique", length = 10)
	public Date getJourLogique() {
		return this.jourLogique;
	}

	public void setJourLogique(Date jourLogique) {
		this.jourLogique = jourLogique;
	}
	@Temporal(TemporalType.DATE)
	@Column(name = "jour", length = 10)
	public Date getJour() {
		return jour;
	}

	public void setJour(Date jour) {
		this.jour = jour;
	}
	@Temporal(TemporalType.TIME)
	@Column(name = "heure", length = 8)
	public Date getHeure() {
		return heure;
	}

	public void setHeure(Date heure) {
		this.heure = heure;
	}

	
	@Column(name = "bckId")
	public Integer getBckId() {
		return this.bckId;
	}

	public void setBckId(Integer bckId) {
		this.bckId = bckId;
	}
	@Column(name = "etat",length=3)
	public String getEtat() {
		return etat;
	}

	public void setEtat(String etat) {
		this.etat = etat;
	}
	@Column(name = "etat_p",nullable=true)
	public String getEtatp() {
		return etatp;
	}

	public void setEtatp(String etatp) {
		this.etatp = etatp;
	}
	@Column(name = "etat_r",nullable=true)
	public String getEtatr() {
		return etatr;
	}

	public void setEtatr(String etatr) {
		this.etatr = etatr;
	}
	@Column(name = "bck_etat",nullable=true)
	public String getBcketat() {
		return bcketat;
	}

	public void setBcketat(String bcketat) {
		this.bcketat = bcketat;
	}
	@Column(name = "position",nullable=true)
	public Integer getPosition() {
		return position;
	}

	public void setPosition(Integer position) {
		this.position = position;
	}
@Transient
	public String getEtaticon() {
	if(etatr.equals("S"))
		return "/resources/img/in.png";
	else
	return "/resources/img/out.png";
	}

	public void setEtaticon(String etaticon) {
		this.etaticon = etaticon;
	}
@Transient
	public List<Mvt> getListmvt() {
		return listmvt;
	}

	public void setListmvt(List<Mvt> listmvt) {
		this.listmvt = listmvt;
	}
}
