package org.bio.model;

// Generated 26 mars 2014 09:34:58 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * OperateurRoles generated by hbm2java
 */
@Entity
@Table(name = "operateur_roles")
@Cache(usage=CacheConcurrencyStrategy.READ_WRITE)
public class OperateurRoles implements java.io.Serializable {

	private OperateurRolesId id;
	private Operateur operateur;
	private  Role role;
	private Boolean r;
	private Boolean w;

	public OperateurRoles() {
	}

	public OperateurRoles(OperateurRolesId id, Operateur operateur) {
		this.id = id;
		this.operateur = operateur;
	}

	public OperateurRoles(OperateurRolesId id, Operateur operateur, Boolean r,
			Boolean w) {
		this.id = id;
		this.operateur = operateur;
		this.r = r;
		this.w = w;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idop", column = @Column(name = "idop", nullable = false)),
			@AttributeOverride(name = "idrol", column = @Column(name = "idrol", nullable = false)) })
	public OperateurRolesId getId() {
		return this.id;
	}

	public void setId(OperateurRolesId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idop", nullable = false, insertable = false, updatable = false)
	public Operateur getOperateur() {
		return this.operateur;
	}

	public void setOperateur(Operateur operateur) {
		this.operateur = operateur;
	}

	@Column(name = "r")
	public Boolean getR() {
		return this.r;
	}

	public void setR(Boolean r) {
		this.r = r;
	}

	@Override
	public String toString() {
		return "OperateurRoles [id=" + id + ", operateur=" + operateur
				+ ", role=" + role + ", r=" + r + ", w=" + w + "]";
	}

	@Column(name = "w")
	public Boolean getW() {
		return this.w;
	}

	public void setW(Boolean w) {
		this.w = w;
	}
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idrol", nullable = false, insertable = false, updatable = false)
	public Role getRole() {
		return role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

}
