package org.bio.model;

// Generated 19 mars 2014 17:02:06 by Hibernate Tools 4.0.0

import java.util.Arrays;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * Personnel generated by hbm2java
 */
@Entity
@Cache(usage=CacheConcurrencyStrategy.READ_WRITE)
@Table(name = "personnel")
public class Personnel implements java.io.Serializable {

	private int idper;
	private Terminaux terminaux;
	private String matricule;
	private String nom;
	private String prenom;
	private String adresse;
	private Integer cp;
	private String ville;
	private String cin;
	private byte[] photo;
	private Date debutContrat;
	private Date finContrat;
	private String mail;
	private Date dateNaissance;
	private String typeContrat;
	private Date dateCreation;
	private Boolean actif;
	private String civilite;
	private String telFixe;
	private String telGsm;
	private String bckNom;
	private String bckPrivilege;
	private Integer droitConge;
	private Integer congeAccorde;
	private Integer droitRecuperation;
	private Integer encoursDroitRecuperation;
	private Integer recuperationAccorde;
	private Integer bckIdEnroll;
	private Integer bckId;
	private String infoSupp;
	private String fullname;
	private String photoName;
	private Set<Identification> identifications = new HashSet<Identification>(0);
	private Set<Synthese> syntheses = new HashSet<Synthese>(0);
	private Set<Mvt> mvts = new HashSet<Mvt>(0);
	private Set<Historique> historiques = new HashSet<Historique>(0);
	private Set<HistoriqueCat> historiqueCats = new HashSet<HistoriqueCat>(0);
	private Set<Pointage> pointages = new HashSet<Pointage>(0);
	private Set<Conge> conges = new HashSet<Conge>(0);
	private Set<PersonnelTerminal> personnelTerminals = new HashSet<PersonnelTerminal>(
			0);
	private Set<Operateur> operateurs = new HashSet<Operateur>(0);
	private Set<Document> documents = new HashSet<Document>(0);
	private List<Historique> findHistorique;
	private List<HistoriqueCat> findHistoriqueCat;
	private List<SequenceDetail> currentListDetails;
	private SequenceDetail currentDetailDay;
	private List<Mvt> findmvt;
	private HistoriqueCat currentHisto;
	private Sequence currentSequence;
private Affiliation currentAffiliation;
	public Personnel() {
	}

	public Personnel(int idper) {
		this.idper = idper;
	}

	public Personnel(int idper, Terminaux terminaux, String matricule,
			String nom, String prenom, String adresse, Integer cp,
			String ville, String cin, byte[] photo, Date debutContrat,
			Date finContrat, String mail, Date dateNaissance,
			String typeContrat, Date dateCreation, Boolean actif,
			String civilite, String telFixe, String telGsm, String bckNom,
			String bckPrivilege, Integer droitConge, Integer congeAccorde,
			Integer droitRecuperation, Integer encoursDroitRecuperation,
			Integer recuperationAccorde, Integer bckIdEnroll, Integer bckId,
			String infoSupp, String photoName,
			Set<Identification> identifications, Set<Synthese> syntheses,
			Set<Mvt> mvts, Set<Historique> historiques,
			Set<Pointage> pointages, Set<Conge> conges,
			Set<PersonnelTerminal> personnelTerminals,
			Set<Operateur> operateurs, Set<Document> documents) {
		this.idper = idper;
		this.terminaux = terminaux;
		this.matricule = matricule;
		this.nom = nom;
		this.prenom = prenom;
		this.adresse = adresse;
		this.cp = cp;
		this.ville = ville;
		this.cin = cin;
		this.photo = photo;
		this.debutContrat = debutContrat;
		this.finContrat = finContrat;
		this.mail = mail;
		this.dateNaissance = dateNaissance;
		this.typeContrat = typeContrat;
		this.dateCreation = dateCreation;
		this.actif = actif;
		this.civilite = civilite;
		this.telFixe = telFixe;
		this.telGsm = telGsm;
		this.bckNom = bckNom;
		this.bckPrivilege = bckPrivilege;
		this.droitConge = droitConge;
		this.congeAccorde = congeAccorde;
		this.droitRecuperation = droitRecuperation;
		this.encoursDroitRecuperation = encoursDroitRecuperation;
		this.recuperationAccorde = recuperationAccorde;
		this.bckIdEnroll = bckIdEnroll;
		this.bckId = bckId;
		this.infoSupp = infoSupp;
		this.photoName = photoName;
		this.identifications = identifications;
		this.syntheses = syntheses;
		this.mvts = mvts;
		this.historiques = historiques;
		this.pointages = pointages;
		this.conges = conges;
		this.personnelTerminals = personnelTerminals;
		this.operateurs = operateurs;
		this.documents = documents;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "idper", unique = true, nullable = false)
	public int getIdper() {
		return this.idper;
	}

	public void setIdper(int idper) {
		this.idper = idper;
	}
// d'origine eager
	@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idter")
	public Terminaux getTerminaux() {
		return this.terminaux;
	}

	public void setTerminaux(Terminaux terminaux) {
		this.terminaux = terminaux;
	}

	@Column(name = "matricule", length = 30)
	public String getMatricule() {
		return this.matricule;
	}

	public void setMatricule(String matricule) {
		this.matricule = matricule;
	}

	@Column(name = "nom", length = 30)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "prenom", length = 30)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "adresse", length = 100)
	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	@Column(name = "cp")
	public Integer getCp() {
		return this.cp;
	}

	public void setCp(Integer cp) {
		this.cp = cp;
	}

	@Column(name = "ville", length = 20)
	public String getVille() {
		return this.ville;
	}

	public void setVille(String ville) {
		this.ville = ville;
	}

	@Column(name = "cin")
	public String getCin() {
		return this.cin;
	}

	public void setCin(String cin) {
		this.cin = cin;
	}

	@Lob
	@Column(name = "photo", columnDefinition = "LONGBLOB")
	public byte[] getPhoto() {
		return this.photo;
	}

	public void setPhoto(byte[] photo) {
		this.photo = photo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "debutContrat", length = 10)
	public Date getDebutContrat() {
		return this.debutContrat;
	}

	public void setDebutContrat(Date debutContrat) {
		this.debutContrat = debutContrat;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "finContrat", length = 10)
	public Date getFinContrat() {
		return this.finContrat;
	}

	public void setFinContrat(Date finContrat) {
		this.finContrat = finContrat;
	}

	@Column(name = "mail", length = 30)
	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateNaissance", length = 10)
	public Date getDateNaissance() {
		return this.dateNaissance;
	}

	public void setDateNaissance(Date dateNaissance) {
		this.dateNaissance = dateNaissance;
	}

	@Column(name = "typeContrat", length = 10)
	public String getTypeContrat() {
		return this.typeContrat;
	}

	public void setTypeContrat(String typeContrat) {
		this.typeContrat = typeContrat;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateCreation", length = 10)
	public Date getDateCreation() {
		return this.dateCreation;
	}

	public void setDateCreation(Date dateCreation) {
		this.dateCreation = dateCreation;
	}

	@Column(name = "actif")
	public Boolean getActif() {
		return this.actif;
	}

	public void setActif(Boolean actif) {
		this.actif = actif;
	}

	@Column(name = "civilite", length = 4)
	public String getCivilite() {
		return this.civilite;
	}

	public void setCivilite(String civilite) {
		this.civilite = civilite;
	}

	@Column(name = "telFixe", length = 20)
	public String getTelFixe() {
		return this.telFixe;
	}

	public void setTelFixe(String telFixe) {
		this.telFixe = telFixe;
	}

	@Column(name = "telGsm", length = 20)
	public String getTelGsm() {
		return this.telGsm;
	}

	public void setTelGsm(String telGsm) {
		this.telGsm = telGsm;
	}

	@Column(name = "bckNom", length = 20)
	public String getBckNom() {
		return this.bckNom;
	}

	public void setBckNom(String bckNom) {
		this.bckNom = bckNom;
	}

	@Column(name = "bckPrivilege", length = 20)
	public String getBckPrivilege() {
		return this.bckPrivilege;
	}

	public void setBckPrivilege(String bckPrivilege) {
		this.bckPrivilege = bckPrivilege;
	}

	@Column(name = "droitConge")
	public Integer getDroitConge() {
		return this.droitConge;
	}

	public void setDroitConge(Integer droitConge) {
		this.droitConge = droitConge;
	}

	@Column(name = "congeAccorde")
	public Integer getCongeAccorde() {
		return this.congeAccorde;
	}

	public void setCongeAccorde(Integer congeAccorde) {
		this.congeAccorde = congeAccorde;
	}

	@Column(name = "droitRecuperation")
	public Integer getDroitRecuperation() {
		return this.droitRecuperation;
	}

	public void setDroitRecuperation(Integer droitRecuperation) {
		this.droitRecuperation = droitRecuperation;
	}

	@Column(name = "encoursDroitRecuperation")
	public Integer getEncoursDroitRecuperation() {
		return this.encoursDroitRecuperation;
	}

	public void setEncoursDroitRecuperation(Integer encoursDroitRecuperation) {
		this.encoursDroitRecuperation = encoursDroitRecuperation;
	}

	@Column(name = "recuperationAccorde")
	public Integer getRecuperationAccorde() {
		return this.recuperationAccorde;
	}

	public void setRecuperationAccorde(Integer recuperationAccorde) {
		this.recuperationAccorde = recuperationAccorde;
	}

	@Column(name = "bckIdEnroll")
	public Integer getBckIdEnroll() {
		return this.bckIdEnroll;
	}

	public void setBckIdEnroll(Integer bckIdEnroll) {
		this.bckIdEnroll = bckIdEnroll;
	}

	@Column(name = "bckId")
	public Integer getBckId() {
		return this.bckId;
	}

	public void setBckId(Integer bckId) {
		this.bckId = bckId;
	}

	@Column(name = "infoSupp", length = 100)
	public String getInfoSupp() {
		return this.infoSupp;
	}

	public void setInfoSupp(String infoSupp) {
		this.infoSupp = infoSupp;
	}

	@Column(name = "photoName", length = 100)
	public String getPhotoName() {
		return this.photoName;
	}

	public void setPhotoName(String photoName) {
		this.photoName = photoName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personnel")
	public Set<Identification> getIdentifications() {
		return this.identifications;
	}

	public void setIdentifications(Set<Identification> identifications) {
		this.identifications = identifications;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personnel")
	public Set<Synthese> getSyntheses() {
		return this.syntheses;
	}

	public void setSyntheses(Set<Synthese> syntheses) {
		this.syntheses = syntheses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personnel")
	public Set<Mvt> getMvts() {
		return this.mvts;
	}

	public void setMvts(Set<Mvt> mvts) {
		this.mvts = mvts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personnel")
	public Set<Historique> getHistoriques() {
		return this.historiques;
	}

	public void setHistoriques(Set<Historique> historiques) {
		this.historiques = historiques;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personnel")
	public Set<Pointage> getPointages() {
		return this.pointages;
	}

	public void setPointages(Set<Pointage> pointages) {
		this.pointages = pointages;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personnel")
	public Set<Conge> getConges() {
		return this.conges;
	}

	public void setConges(Set<Conge> conges) {
		this.conges = conges;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personnel")
	public Set<PersonnelTerminal> getPersonnelTerminals() {
		return this.personnelTerminals;
	}

	public void setPersonnelTerminals(Set<PersonnelTerminal> personnelTerminals) {
		this.personnelTerminals = personnelTerminals;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personnel")
	public Set<Operateur> getOperateurs() {
		return this.operateurs;
	}

	public void setOperateurs(Set<Operateur> operateurs) {
		this.operateurs = operateurs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personnel")
	public Set<Document> getDocuments() {
		return this.documents;
	}

	public void setDocuments(Set<Document> documents) {
		this.documents = documents;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personnel")
	public Set<HistoriqueCat> getHistoriqueCats() {
		return historiqueCats;
	}

	@Override
	public String toString() {
		return "Personnel [idper=" + idper + ", terminaux=" + terminaux
				+ ", matricule=" + matricule + ", nom=" + nom + ", prenom="
				+ prenom;
	}

	public void setHistoriqueCats(Set<HistoriqueCat> historiqueCats) {
		this.historiqueCats = historiqueCats;
	}

	@Transient
	public List<Historique> getFindHistorique() {
		return findHistorique;
	}

	public void setFindHistorique(List<Historique> findHistorique) {
		this.findHistorique = findHistorique;
	}

	@Transient
	public List<HistoriqueCat> getFindHistoriqueCat() {
		return findHistoriqueCat;
	}

	public void setFindHistoriqueCat(List<HistoriqueCat> findHistoriqueCat) {
		this.findHistoriqueCat = findHistoriqueCat;
	}

	@Transient
	public List<Mvt> getFindmvt() {
		return findmvt;
	}

	public void setFindmvt(List<Mvt> findmvt) {
		this.findmvt = findmvt;
	}

	@Transient
	public List<SequenceDetail> getCurrentListDetails() {
		return currentListDetails;
	}

	public void setCurrentListDetails(List<SequenceDetail> currentListDetails) {
		this.currentListDetails = currentListDetails;
	}

	@Transient
	public HistoriqueCat getCurrentHisto() {
		return currentHisto;
	}

	public void setCurrentHisto(HistoriqueCat currentHisto) {
		this.currentHisto = currentHisto;
	}

	@Transient
	public Sequence getCurrentSequence() {
		return currentSequence;
	}

	public void setCurrentSequence(Sequence currentSequence) {
		this.currentSequence = currentSequence;
	}
@Transient
	public SequenceDetail getCurrentDetailDay() {
		return currentDetailDay;
	}

	public void setCurrentDetailDay(SequenceDetail currentDetailDay) {
		this.currentDetailDay = currentDetailDay;
	}
@Column(name="fullname",length=100)
	public String getFullname() {
		return fullname;
	}

	public void setFullname(String fullname) {
		this.fullname = fullname;
	}
@Transient
	public Affiliation getCurrentAffiliation() {
		return currentAffiliation;
	}

	public void setCurrentAffiliation(Affiliation affiliation) {
		this.currentAffiliation = affiliation;
	}
	
	public String convert()
	{
		return ""+idper;
	}
	
	@Override
	public boolean equals(Object p){
		   return (this.idper == (((Personnel)p).getIdper()));
		}



}
