package org.bio.model;

// Generated 26 mars 2014 09:34:58 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "role")
@Cache(usage=CacheConcurrencyStrategy.READ_WRITE)
public class Role implements java.io.Serializable {

	@Override
	public String toString() {
		return "Role [idrol=" + idrol + ", nom=" + nom + ", dateCreation="
				+ dateCreation + ", roleName=" + roleName + ", roleNameDe="
				+ roleNameDe + ", roleNameIi=" + roleNameIi + ", roleNameEn="
				+ roleNameEn + ", typeDe=" + typeDe + ", typeEn=" + typeEn
				+ ", typeIt=" + typeIt + ", position=" + position + ", url="
				+ url + ", editable=" + editable + ", icon=" + icon + ", type="
				+ type + ", rolePages=" + rolePages + "]";
	}

	private Integer idrol;
	private String nom;
	private Date dateCreation;
	private String roleName;
	private String roleNameDe;
	private String roleNameIi;
	private String roleNameEn;
	private String typeDe;
	private String typeEn;
	private String typeIt;
	private String position;
	private String url;
	private Boolean editable;
	private String icon;
	private String type;
	private Set<RolePage> rolePages = new HashSet<RolePage>(0);

	public Role() {
	}

	public Role(String nom, Date dateCreation, String roleName, String url,
			String icon, String type, Set<RolePage> rolePages,boolean editable) {
		this.nom = nom;
		this.dateCreation = dateCreation;
		this.roleName = roleName;
		this.url = url;
		this.icon = icon;
		this.type = type;
		this.editable=editable;
		this.rolePages = rolePages;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idrol", unique = true, nullable = false)
	public Integer getIdrol() {
		return this.idrol;
	}

	public void setIdrol(Integer idrol) {
		this.idrol = idrol;
	}

	@Column(name = "nom", length = 20)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateCreation", length = 19)
	public Date getDateCreation() {
		return this.dateCreation;
	}

	public void setDateCreation(Date dateCreation) {
		this.dateCreation = dateCreation;
	}

	@Column(name = "roleName", length = 45)
	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	@Column(name = "url", length = 100)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "icon", length = 45)
	public String getIcon() {
		return this.icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

	@Column(name = "type", length = 50)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "role")
	public Set<RolePage> getRolePages() {
		return this.rolePages;
	}

	public void setRolePages(Set<RolePage> rolePages) {
		this.rolePages = rolePages;
	}
	@Column(name = "roleNameDe", length = 50)
	public String getRoleNameDe() {
		return roleNameDe;
	}

	public void setRoleNameDe(String roleNameDe) {
		this.roleNameDe = roleNameDe;
	}
	@Column(name = "roleNameIt", length = 50)
	public String getRoleNameIi() {
		return roleNameIi;
	}
	
	public void setRoleNameIi(String roleNameIi) {
		this.roleNameIi = roleNameIi;
	}
	@Column(name = "roleNameEn", length = 50)
	public String getRoleNameEn() {
		return roleNameEn;
	}

	public void setRoleNameEn(String roleNameEn) {
		this.roleNameEn = roleNameEn;
	}
	@Column(name = "typeDe", length = 50)
	public String getTypeDe() {
		return typeDe;
	}

	public void setTypeDe(String typeDe) {
		this.typeDe = typeDe;
	}
	@Column(name = "typeEn", length = 50)
	public String getTypeEn() {
		return typeEn;
	}

	public void setTypeEn(String typeEn) {
		this.typeEn = typeEn;
	}
	@Column(name = "typeIt", length = 50)
	public String getTypeIt() {
		return typeIt;
	}

	public void setTypeIt(String typeIt) {
		this.typeIt = typeIt;
	}

	public String getPosition() {
		return position;
	}
	@Column(name = "position", length = 1)
	public void setPosition(String position) {
		this.position = position;
	}
	
	@Column(name="editable")
	public Boolean getEditable() {
		return editable;
	}

	public void setEditable(Boolean editable) {
		this.editable = editable;
	}


}
