package org.bio.model;

// Generated 19 mars 2014 17:02:06 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

/**
 * SequenceDetailId generated by hbm2java
 */
@Embeddable
public class SequenceDetailId implements java.io.Serializable {

	private int idseqd;
	private int jour;

	public SequenceDetailId() {
	}

	public SequenceDetailId(int idseqd, int jour) {
		this.idseqd = idseqd;
		this.jour = jour;
	}
	
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "idseqd", nullable = false)
	public int getIdseqd() {
		return this.idseqd;
	}

	public void setIdseqd(int idseqd) {
		this.idseqd = idseqd;
	}

	@Column(name = "jour", nullable = false, length = 10)
	public int getJour() {
		return this.jour;
	}

	public void setJour(int jour) {
		this.jour = jour;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SequenceDetailId))
			return false;
		SequenceDetailId castOther = (SequenceDetailId) other;

		return (this.getIdseqd() == castOther.getIdseqd())
				&& ((this.getJour() == castOther.getJour()) || (this.getJour() == 0
						&& castOther.getJour() == 0 && this.getJour()==(castOther.getJour())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdseqd();
		result = 37 * result +  this.getJour();
		return result;
	}

}
