package org.bio.model;

// Generated 19 mars 2014 17:02:06 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Horaires generated by hbm2java
 */
@Entity
@Table(name = "horaires")
public class Horaires implements java.io.Serializable {

	private HorairesId id;
	private Sequence sequence;
	private Calendrier calendrier;
	private Categorie categorie;

	public Horaires() {
	}

	public Horaires(HorairesId id, Sequence sequence, Calendrier calendrier,
			Categorie categorie) {
		this.id = id;
		this.sequence = sequence;
		this.calendrier = calendrier;
		this.categorie = categorie;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idcat", column = @Column(name = "idcat", nullable = false)),
			@AttributeOverride(name = "idcal", column = @Column(name = "idcal", nullable = false)) })
	public HorairesId getId() {
		return this.id;
	}

	public void setId(HorairesId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idseq", nullable = false)
	public Sequence getSequence() {
		return this.sequence;
	}

	public void setSequence(Sequence sequence) {
		this.sequence = sequence;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idcal", nullable = false, insertable = false, updatable = false)
	public Calendrier getCalendrier() {
		return this.calendrier;
	}

	public void setCalendrier(Calendrier calendrier) {
		this.calendrier = calendrier;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idcat", nullable = false, insertable = false, updatable = false)
	public Categorie getCategorie() {
		return this.categorie;
	}

	public void setCategorie(Categorie categorie) {
		this.categorie = categorie;
	}

}
