package org.bio.model;

// Generated 19 mars 2014 17:02:06 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Calendrier generated by hbm2java
 */
@Entity
@Table(name = "calendrier")
public class Calendrier implements java.io.Serializable {

	private int idcal;
	private String designation;
	private Date dateDebut;
	private Date dateFin;
	private String typeCal;
	private Set<Horaires> horaireses = new HashSet<Horaires>(0);
	private Set<GlobalHistorique> globalHistoriques = new HashSet<GlobalHistorique>(
			0);

	public Calendrier() {
	}

	public Calendrier(int idcal) {
		this.idcal = idcal;
	}

	public Calendrier(int idcal, String designation, Date dateDebut,
			Date dateFin, String typeCal, Set<Horaires> horaireses,
			Set<GlobalHistorique> globalHistoriques) {
		this.idcal = idcal;
		this.designation = designation;
		this.dateDebut = dateDebut;
		this.dateFin = dateFin;
		this.typeCal = typeCal;
		this.horaireses = horaireses;
		this.globalHistoriques = globalHistoriques;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "idcal", unique = true, nullable = false)
	public int getIdcal() {
		return this.idcal;
	}

	public void setIdcal(int idcal) {
		this.idcal = idcal;
	}

	@Column(name = "designation", length = 25)
	public String getDesignation() {
		return this.designation;
	}

	public void setDesignation(String designation) {
		this.designation = designation;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateDebut", length = 10)
	public Date getDateDebut() {
		return this.dateDebut;
	}

	public void setDateDebut(Date dateDebut) {
		this.dateDebut = dateDebut;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateFin", length = 10)
	public Date getDateFin() {
		return this.dateFin;
	}

	public void setDateFin(Date dateFin) {
		this.dateFin = dateFin;
	}

	@Column(name = "typeCal", length = 10)
	public String getTypeCal() {
		return this.typeCal;
	}

	public void setTypeCal(String typeCal) {
		this.typeCal = typeCal;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "calendrier")
	public Set<Horaires> getHoraireses() {
		return this.horaireses;
	}

	public void setHoraireses(Set<Horaires> horaireses) {
		this.horaireses = horaireses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "calendrier")
	public Set<GlobalHistorique> getGlobalHistoriques() {
		return this.globalHistoriques;
	}

	public void setGlobalHistoriques(Set<GlobalHistorique> globalHistoriques) {
		this.globalHistoriques = globalHistoriques;
	}

}
