package org.bio.model;

// Generated 19 mars 2014 17:02:06 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Conge generated by hbm2java
 */
@Entity
@Table(name = "conge")
public class Conge implements java.io.Serializable {

	private int idcon;
	private Motif motif;
	private Personnel personnel;
	private Date debut;
	private Date fin;
	private String type;

	public Conge() {
	}

	public Conge(int idcon, Motif motif, Personnel personnel) {
		this.idcon = idcon;
		this.motif = motif;
		this.personnel = personnel;
	}

	public Conge(int idcon, Motif motif, Personnel personnel, Date debut,
			Date fin, String type) {
		this.idcon = idcon;
		this.motif = motif;
		this.personnel = personnel;
		this.debut = debut;
		this.fin = fin;
		this.type = type;
	}
	
	public Conge(int idcon, Motif motif, Personnel personnel, Date debut,
			Date fin) {
		this.idcon = idcon;
		this.motif = motif;
		this.personnel = personnel;
		this.debut = debut;
		this.fin = fin;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "idcon", unique = true, nullable = false)
	public int getIdcon() {
		return this.idcon;
	}

	public void setIdcon(int idcon) {
		this.idcon = idcon;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idmot", nullable = false)
	public Motif getMotif() {
		return this.motif;
	}

	public void setMotif(Motif motif) {
		this.motif = motif;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idper", nullable = false)
	public Personnel getPersonnel() {
		return this.personnel;
	}

	public void setPersonnel(Personnel personnel) {
		this.personnel = personnel;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "debut", length = 10)
	public Date getDebut() {
		return this.debut;
	}

	public void setDebut(Date debut) {
		this.debut = debut;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fin", length = 10)
	public Date getFin() {
		return this.fin;
	}

	public void setFin(Date fin) {
		this.fin = fin;
	}

	@Column(name = "type")
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
