package org.bio.model;

// Generated 26 mars 2014 09:34:58 by Hibernate Tools 4.0.0

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;
import org.springframework.stereotype.Component;

/**
 * Operateur generated by hbm2java
 */
@Entity
@Table(name = "operateur")
@Cache(usage=CacheConcurrencyStrategy.TRANSACTIONAL,include="ALL")
public class Operateur implements java.io.Serializable {

	private Integer idop;
	private Personnel personnel;
	private String login;
	private String motPasse;
	private String theme;
	private String langue;
	private Set<Affiliation> affiliations = new HashSet<Affiliation>(0);
	private Set<Trace> traces = new HashSet<Trace>(0);
	private Set<OperateurRoles> operateurRoleses = new HashSet<OperateurRoles>(
			0);
	private List<Affiliation> listaffiliations =new ArrayList<Affiliation>();
private List<OperateurRoles> listroles = new ArrayList<OperateurRoles>();
	public Operateur() {
	}

	public Operateur(String login, String motPasse) {
		this.login = login;
		this.motPasse = motPasse;
	}

	public Operateur(Personnel personnel, String login, String motPasse,
			String theme, Set<Affiliation> affiliations, Set<Trace> traces,
			Set<OperateurRoles> operateurRoleses) {
		this.personnel = personnel;
		this.login = login;
		this.motPasse = motPasse;
		this.theme = theme;
		this.affiliations = affiliations;
		this.traces = traces;
		this.operateurRoleses = operateurRoleses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idop", unique = true, nullable = false)
	public Integer getIdop() {
		return this.idop;
	}

	public void setIdop(Integer idop) {
		this.idop = idop;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idper")
	public Personnel getPersonnel() {
		return this.personnel;
	}

	public void setPersonnel(Personnel personnel) {
		this.personnel = personnel;
	}

	@Column(name = "login", nullable = false, length = 10)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "motPasse", nullable = false, length = 200)
	public String getMotPasse() {
		return this.motPasse;
	}

	public void setMotPasse(String motPasse) {
		this.motPasse = motPasse;
	}

	@Column(name = "theme", length = 20)
	public String getTheme() {
		return this.theme;
	}

	public void setTheme(String theme) {
		this.theme = theme;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@Fetch(FetchMode.JOIN)
	@JoinTable(name = "operateur_affiliation", catalog = "BiopointKb2i", joinColumns = { @JoinColumn(name = "idop", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "idaff", nullable = false, updatable = false) })
	public Set<Affiliation> getAffiliations() {
		return this.affiliations;
	}

	public void setAffiliations(Set<Affiliation> affiliations) {
		this.affiliations = affiliations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "operateur")
	public Set<Trace> getTraces() {
		return this.traces;
	}

	public void setTraces(Set<Trace> traces) {
		this.traces = traces;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "operateur",cascade={CascadeType.REMOVE, CascadeType.MERGE})
	public Set<OperateurRoles> getOperateurRoleses() {
		return this.operateurRoleses;
	}

	public void setOperateurRoleses(Set<OperateurRoles> operateurRoleses) {
		this.operateurRoleses = operateurRoleses;
	}
@Transient
	public List<OperateurRoles> getListroles() {
		return listroles;
	}

	public void setListroles(List<OperateurRoles> listroles) {

		this.listroles = listroles;
	}
@Transient
	public List<Affiliation> getListaffiliations() {
	listaffiliations = new ArrayList<Affiliation>();
	listaffiliations.addAll(affiliations);
		return listaffiliations;
	}

	public void setListaffiliations(List<Affiliation> listaffiliations) {
		this.listaffiliations = listaffiliations;
	}
	@Column(name = "langue", length = 2)
	public String getLangue() {
		return langue;
	}

	public void setLangue(String langue) {
		this.langue = langue;
	}

}
