package org.bio.model;


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Calendrier generated by hbm2java
 */
@Entity
@Table(name = "rapport", catalog = "BiopointKb2i")
public class Rapport implements java.io.Serializable {
	
	private int idrapport;
	private ModeleRapport idrapportGroup;
	private String nomRapport;
	private Date dateDebut;
	private Date dateFin;
	private int periode;
	private int indication;
	
	public Rapport()
	{}
	public Rapport(int idrapport)
	{this.idrapport= idrapport;}
	public void Rapport(int idrapport, ModeleRapport idrapportGroup, String nomRapport, Date dateDebut, Date dateFin,int periode,int indication)
	{
		this.idrapport=idrapport;this.idrapportGroup=idrapportGroup;this.nomRapport=nomRapport;
		this.dateDebut=dateDebut;this.dateFin=dateFin;this.periode=periode;this.indication=indication;
	}
	
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "idrapport", unique = true, nullable = false)
	public int getidrapport() {
		return this.idrapport;
	}

	public void setidrapport(int idrapport) {
		this.idrapport = idrapport;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "rapportGroup")
	public ModeleRapport getidrapportGroup() {
		return this.idrapportGroup;
	}

	public void setidrapportGroup(ModeleRapport idrapportGroup) {
		this.idrapportGroup = idrapportGroup;
	}

	@Column(name = "nomRapport", length = 25)
	public String getnomRapport() {
		return this.nomRapport;
	}

	public void setnomRapport(String nomRapport) {
		this.nomRapport = nomRapport;
	}
	
	@Temporal(TemporalType.DATE)
	@Column(name = "dateDebut", length = 10)
	public Date getDateDebut() {
		return this.dateDebut;
	}

	public void setDateDebut(Date dateDebut) {
		this.dateDebut = dateDebut;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateFin", length = 10)
	public Date getDateFin() {
		return this.dateFin;
	}

	public void setDateFin(Date dateFin) {
		this.dateFin = dateFin;
	}
	
	
	@Column(name = "periode", length = 25)
	public int getPeriode() {
		return periode;
	}
	public void setPeriode(int periode) {
		this.periode = periode;
	}
	
	@Column(name = "indication", length = 25)
	public int getIndication() {
		return indication;
	}
	public void setIndication(int indication) {
		this.indication = indication;
	}
}
