package org.bio.model;

// Generated 19 mars 2014 17:02:06 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Sequence generated by hbm2java
 */
@Entity
@Table(name = "sequence")
public class Sequence implements java.io.Serializable {

	private int idseq;
	private String desigSeq;
	private String typeSeq;
	private Integer longueurSequence;
	private Set<Horaires> horaireses = new HashSet<Horaires>(0);

	public Sequence() {
	}

	public Sequence(int idseq) {
		this.idseq = idseq;
	}

	public Sequence(int idseq, String desigSeq, String typeSeq,
			Integer longueurSequence, Set<Horaires> horaireses) {
		this.idseq = idseq;
		this.desigSeq = desigSeq;
		this.typeSeq = typeSeq;
		this.longueurSequence = longueurSequence;
		this.horaireses = horaireses;
	}
	
	public boolean equals(Sequence seq)
	{
		return(this.desigSeq.equals(seq.desigSeq)&& this.idseq==seq.idseq);
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "idseq", unique = true, nullable = false)
	public int getIdseq() {
		return this.idseq;
	}

	public void setIdseq(int idseq) {
		this.idseq = idseq;
	}

	@Column(name = "DesigSeq", length = 20)
	public String getDesigSeq() {
		return this.desigSeq;
	}

	public void setDesigSeq(String desigSeq) {
		this.desigSeq = desigSeq;
	}

	@Column(name = "typeSeq", length = 20)
	public String getTypeSeq() {
		return this.typeSeq;
	}

	public void setTypeSeq(String typeSeq) {
		this.typeSeq = typeSeq;
	}

	@Column(name = "longueurSequence")
	public Integer getLongueurSequence() {
		return this.longueurSequence;
	}

	public void setLongueurSequence(Integer longueurSequence) {
		this.longueurSequence = longueurSequence;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sequence")
	public Set<Horaires> getHoraireses() {
		return this.horaireses;
	}

	public void setHoraireses(Set<Horaires> horaireses) {
		this.horaireses = horaireses;
	}

}
