package org.bio.model;

// Generated 19 mars 2014 17:02:06 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Societe generated by hbm2java
 */
@Entity
@Table(name = "societe")
@Cache(usage=CacheConcurrencyStrategy.READ_WRITE)
public class Societe implements java.io.Serializable {

	private int idaff;
	private Affiliation affiliation;
	private String numTel;
	private String numFax;
	private String adresse;
	private byte[] logo;
	private String mail;
	private String pays;
	private String ville;
	private Integer cp;
	private String siteWeb;
	private String statut;
	private String logoName;
	public Societe() {
	}

	public Societe(Affiliation affiliation) {
		this.affiliation = affiliation;
	}

	public Societe(Affiliation affiliation, String numTel, String numFax,
			String adresse, byte[] logo, String mail, String pays,
			String ville, Integer cp, String siteWeb, String statut) {
		this.affiliation = affiliation;
		this.numTel = numTel;
		this.numFax = numFax;
		this.adresse = adresse;
		this.logo = logo;
		this.mail = mail;
		this.pays = pays;
		this.ville = ville;
		this.cp = cp;
		this.siteWeb = siteWeb;
		this.statut = statut;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "affiliation"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "idaff", unique = true, nullable = false)
	public int getIdaff() {
		return this.idaff;
	}

	public void setIdaff(int idaff) {
		this.idaff = idaff;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Affiliation getAffiliation() {
		return this.affiliation;
	}

	public void setAffiliation(Affiliation affiliation) {
		this.affiliation = affiliation;
	}

	@Column(name = "numTel", length = 20)
	public String getNumTel() {
		return this.numTel;
	}

	public void setNumTel(String numTel) {
		this.numTel = numTel;
	}

	@Column(name = "numFax", length = 20)
	public String getNumFax() {
		return this.numFax;
	}

	public void setNumFax(String numFax) {
		this.numFax = numFax;
	}

	@Column(name = "adresse", length = 100)
	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	@Column(name = "logo")
	public byte[] getLogo() {
		return this.logo;
	}

	public void setLogo(byte[] logo) {
		this.logo = logo;
	}

	@Column(name = "mail", length = 20)
	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	@Column(name = "pays", length = 20)
	public String getPays() {
		return this.pays;
	}

	public void setPays(String pays) {
		this.pays = pays;
	}

	@Column(name = "ville", length = 10)
	public String getVille() {
		return this.ville;
	}

	public void setVille(String ville) {
		this.ville = ville;
	}

	@Column(name = "cp")
	public Integer getCp() {
		return this.cp;
	}

	public void setCp(Integer cp) {
		this.cp = cp;
	}

	@Column(name = "siteWeb", length = 20)
	public String getSiteWeb() {
		return this.siteWeb;
	}

	public void setSiteWeb(String siteWeb) {
		this.siteWeb = siteWeb;
	}

	@Column(name = "statut", length = 10)
	public String getStatut() {
		return this.statut;
	}

	public void setStatut(String statut) {
		this.statut = statut;
	}

@Column(name="logoname")
	public String getLogoName() {
		return logoName;
	}

	public void setLogoName(String logoName) {
		this.logoName = logoName;
	}

}
