package org.bio.model;

// Generated 19 mars 2014 17:02:06 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PersonnelTerminalId generated by hbm2java
 */
@Embeddable
public class PersonnelTerminalId implements java.io.Serializable {

	private int idper;
	private int idter;

	public PersonnelTerminalId() {
	}

	public PersonnelTerminalId(int idper, int idter) {
		this.idper = idper;
		this.idter = idter;
	}

	@Column(name = "idper", nullable = false)
	public int getIdper() {
		return this.idper;
	}

	public void setIdper(int idper) {
		this.idper = idper;
	}

	@Column(name = "idter", nullable = false)
	public int getIdter() {
		return this.idter;
	}

	public void setIdter(int idter) {
		this.idter = idter;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PersonnelTerminalId))
			return false;
		PersonnelTerminalId castOther = (PersonnelTerminalId) other;

		return (this.getIdper() == castOther.getIdper())
				&& (this.getIdter() == castOther.getIdter());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdper();
		result = 37 * result + this.getIdter();
		return result;
	}

}
