package org.bio.model;

// Generated 19 mars 2014 17:02:06 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Page generated by hbm2java
 */
@Entity
@Table(name = "page", catalog = "BiopointKb2i")
public class Page implements java.io.Serializable {

	private int idpag;
	private String nom;
	private Set<RolePage> rolePages = new HashSet<RolePage>(0);

	public Page() {
	}

	public Page(int idpag) {
		this.idpag = idpag;
	}

	public Page(int idpag, String nom, Set<RolePage> rolePages) {
		this.idpag = idpag;
		this.nom = nom;
		this.rolePages = rolePages;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "idpag", unique = true, nullable = false)
	public int getIdpag() {
		return this.idpag;
	}

	public void setIdpag(int idpag) {
		this.idpag = idpag;
	}

	@Column(name = "nom", length = 100)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "page")
	public Set<RolePage> getRolePages() {
		return this.rolePages;
	}

	public void setRolePages(Set<RolePage> rolePages) {
		this.rolePages = rolePages;
	}

}
