package org.bio.model;

// Generated 19 mars 2014 17:02:06 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RolePageId generated by hbm2java
 */
@Embeddable
public class RolePageId implements java.io.Serializable {

	private int idrol;
	private int idpag;

	public RolePageId() {
	}

	public RolePageId(int idrol, int idpag) {
		this.idrol = idrol;
		this.idpag = idpag;
	}

	@Column(name = "idrol", nullable = false)
	public int getIdrol() {
		return this.idrol;
	}

	public void setIdrol(int idrol) {
		this.idrol = idrol;
	}

	@Column(name = "idpag", nullable = false)
	public int getIdpag() {
		return this.idpag;
	}

	public void setIdpag(int idpag) {
		this.idpag = idpag;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RolePageId))
			return false;
		RolePageId castOther = (RolePageId) other;

		return (this.getIdrol() == castOther.getIdrol())
				&& (this.getIdpag() == castOther.getIdpag());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdrol();
		result = 37 * result + this.getIdpag();
		return result;
	}

}
