package org.bio.model;

// Generated 19 mars 2014 17:02:06 by Hibernate Tools 4.0.0

import java.io.BufferedReader;
import java.io.PrintWriter;
import java.net.Socket;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * Terminaux generated by hbm2java
 */
@Entity
@Cache(usage=CacheConcurrencyStrategy.READ_WRITE)
@Table(name = "terminaux")
public class Terminaux implements java.io.Serializable {

	@Override
	public String toString() {
		return idter + " " + type + " "
				+ libelle;
	}

	private int idter;
	private String type;
	private String libelle;
	private String ip;
	private Boolean actif;
	private Integer rsVitesse;
	private Integer rsCom;
	private Boolean pointage;
	private Boolean enrollement;
	private Integer nserie;
	private Integer cle;
	private String port;
	private String platform;
	private Integer deviceId;
	private String etat ="Déconnecté";
	private Socket client;
	private List<Mvt> loadedMvt;
	private BufferedReader in;
	private PrintWriter out;
	private String password;
	private String serverIp;
	private String ServerPort;
	private boolean connected = false;
	private Set<PersonnelTerminal> personnelTerminals = new HashSet<PersonnelTerminal>(0);
	private Set<Personnel> personnels = new HashSet<Personnel>(0);
	private Set<Mvt> mvts = new HashSet<Mvt>(0);
private Integer progress;
	public Terminaux() {
		progress=0;
	}

	public Terminaux(int idter) {
		this.idter = idter;
		progress=0;

	}

	public Terminaux(int idter, String type, String libelle, String ip,
			Boolean actif, Integer rsVitesse, Integer rsCom, Boolean pointage,
			Boolean enrollement, Integer nserie, Integer cle,
			Set<PersonnelTerminal> personnelTerminals,
			Set<Personnel> personnels, Set<Mvt> mvts) {
		this.idter = idter;
		this.type = type;
		this.libelle = libelle;
		this.ip = ip;
		this.actif = actif;
		this.rsVitesse = rsVitesse;
		this.rsCom = rsCom;
		this.pointage = pointage;
		this.enrollement = enrollement;
		this.nserie = nserie;
		this.cle = cle;
		this.personnelTerminals = personnelTerminals;
		this.personnels = personnels;
		this.mvts = mvts;
	}
	
	////////////////// MODIFICATION ///////////////
	
	public Terminaux(String type, String libelle, String ip,
			Boolean actif, Integer rsVitesse, Integer rsCom, Boolean pointage,
			Boolean enrollement, Integer nserie, Integer cle)
			 {
				this.type = type;
				this.libelle = libelle;
				this.ip = ip;
				this.actif = actif;
				this.rsVitesse = rsVitesse;
				this.rsCom = rsCom;
				this.pointage = pointage;
				this.enrollement = enrollement;
				this.nserie = nserie;
				this.cle = cle;
			 }
	
	///////////////////////////////////////////////

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "idter", unique = true, nullable = false)
	public int getIdter() {
		return this.idter;
	}

	public void setIdter(int idter) {
		this.idter = idter;
	}

	@Column(name = "type", length = 20)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "libelle", length = 20)
	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	@Column(name = "ip", length = 15)
	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	@Column(name = "actif")
	public Boolean getActif() {
		return this.actif;
	}

	public void setActif(Boolean actif) {
		this.actif = actif;
	}

	@Column(name = "rsVitesse")
	public Integer getRsVitesse() {
		return this.rsVitesse;
	}

	public void setRsVitesse(Integer rsVitesse) {
		this.rsVitesse = rsVitesse;
	}

	@Column(name = "rsCom")
	public Integer getRsCom() {
		return this.rsCom;
	}

	public void setRsCom(Integer rsCom) {
		this.rsCom = rsCom;
	}

	@Column(name = "pointage")
	public Boolean getPointage() {
		return this.pointage;
	}

	public void setPointage(Boolean pointage) {
		this.pointage = pointage;
	}

	@Column(name = "enrollement")
	public Boolean getEnrollement() {
		return this.enrollement;
	}

	public void setEnrollement(Boolean enrollement) {
		this.enrollement = enrollement;
	}

	@Column(name = "nSerie")
	public Integer getNserie() {
		return this.nserie;
	}

	public void setNserie(Integer nserie) {
		this.nserie = nserie;
	}

	@Column(name = "cle")
	public Integer getCle() {
		return this.cle;
	}

	public void setCle(Integer cle) {
		this.cle = cle;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "terminaux")
	public Set<PersonnelTerminal> getPersonnelTerminals() {
		return this.personnelTerminals;
	}

	public void setPersonnelTerminals(Set<PersonnelTerminal> personnelTerminals) {
		this.personnelTerminals = personnelTerminals;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "terminaux")
	public Set<Personnel> getPersonnels() {
		return this.personnels;
	}

	public void setPersonnels(Set<Personnel> personnels) {
		this.personnels = personnels;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "terminaux")
	public Set<Mvt> getMvts() {
		return this.mvts;
	}

	public void setMvts(Set<Mvt> mvts) {
		this.mvts = mvts;
	}
	@Column(name = "port", length = 5)
	public String getPort() {
		return port;
	}

	public void setPort(String port) {
		this.port = port;
	}
	@Column(name = "plateform", length = 45)
	public String getPlatform() {
		return platform;
	}

	public void setPlatform(String platform) {
		this.platform = platform;
	}
@Transient
	public String getEtat() {
		return etat;
	}

	public void setEtat(String etat) {
		this.etat = etat;
	}
@Transient
	public boolean isConnected() {
		
		return connected;
	}

	public void setConnected(boolean connected) {
		this.connected = connected;
	}
	@Transient
	public Socket getClient() {
		return client;
	}

	public void setClient(Socket client) {
		this.client = client;
	}
	@Transient
	public BufferedReader getIn() {
		return in;
	}
	public void setIn(BufferedReader in) {
		this.in = in;
	}
	@Transient
	public PrintWriter getOut() {
		return out;
	}

	public void setOut(PrintWriter out) {
		this.out = out;
	}
@Transient
	public List<Mvt> getLoadedMvt() {
		return loadedMvt;
	}

	public void setLoadedMvt(List<Mvt> loadedMvt) {
		this.loadedMvt = loadedMvt;
	}
@Transient
	public Integer getProgress() {
	if(progress>100)
progress=100;
		return progress;
	}

	public void setProgress(Integer progress) {
		this.progress = progress;
	}
@Column(name="deviceId",nullable=true)
	public Integer getDeviceId() {
		return deviceId;
	}

	public void setDeviceId(Integer deviceId) {
		this.deviceId = deviceId;
	}
@Column(name="password",length=45)
	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}
	@Column(name = "serverIp")
	public String getServerIp() {
		return serverIp;
	}

	public void setServerIp(String serverIp) {
		this.serverIp = serverIp;
	}
	@Column(name = "serverPort")
	public String getServerPort() {
		return ServerPort;
	}

	public void setServerPort(String serverPort) {
		ServerPort = serverPort;
	}

}
