package org.bio.model;

// Generated 19 mars 2014 17:02:06 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.Valid;
import javax.validation.constraints.AssertTrue;
import javax.validation.constraints.Future;
import javax.validation.constraints.Past;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.hibernate.annotations.CascadeType;

/**
 * Historique generated by hbm2java
 */
@Entity
@Table(name = "historique")
public class Historique implements java.io.Serializable {

	private int idhis;
	private Affiliation affiliation;
	private Personnel personnel;
	private Categorie categorie;
	private Date du;
	private Date au;
	private Affiliation societe;
	private String desigSte;
	private int idste;
	public Historique() {
	}

	public Historique(int idhis, Affiliation affiliation, Personnel personnel,
			Categorie categorie, Affiliation ste,int idste) {
		this.idhis = idhis;
		this.affiliation = affiliation;
		this.personnel = personnel;
		this.categorie = categorie;
		this.societe=ste;
		this.idste=idste;
	}

	public Historique(int idhis, Affiliation affiliation, Personnel personnel,
			Categorie categorie,Affiliation ste,Date du, Date au,int idste) {
		this.idhis = idhis;
		this.affiliation = affiliation;
		this.personnel = personnel;
		this.categorie = categorie;
		this.societe=ste;
		this.du = du;
		this.au = au;
		this.idste=idste;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "idhis", unique = true, nullable = false)
	public int getIdhis() {
		return this.idhis;
	}

	public void setIdhis(int idhis) {
		this.idhis = idhis;
	}
@Cache(usage=CacheConcurrencyStrategy.READ_WRITE)
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idaff", nullable = false)
	public Affiliation getAffiliation() {
		return this.affiliation;
	}

	public void setAffiliation(Affiliation affiliation) {
		this.affiliation = affiliation;
	}
	
	@Cache(usage=CacheConcurrencyStrategy.READ_WRITE)
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idste", nullable = false,insertable= false, updatable= false)
	public Affiliation getSociete() {
		return this.societe;
	}

	public void setSociete(Affiliation societe) {
		this.societe = societe;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idper", nullable = false)
	public Personnel getPersonnel() {
		return this.personnel;
	}

	public void setPersonnel(Personnel personnel) {
		this.personnel = personnel;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcat", nullable = true)
	public Categorie getCategorie() {
		return this.categorie;
	}

	public void setCategorie(Categorie categorie) {
		this.categorie = categorie;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Du", length = 10)
	public Date getDu() {
		return this.du;
	}

	public void setDu(Date du) {
		this.du = du;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Au", length = 10)
	public Date getAu() {
		return this.au;
	}

	public void setAu(Date au) {
		this.au = au;
	}

	@Override
	public String toString() {
		return getAffiliation().toString();
	}
@Column(name="desigSte")
	public String getDesigSte() {
		return desigSte;
	}

	public void setDesigSte(String desigSte) {
		this.desigSte = desigSte;
	}

	
	@Column(name="idste")
	public int getIdste() {
		return idste;
	}

	public void setIdste(int idste) {
		this.idste = idste;
	}

}
