package org.bio.model;

// Generated 19 mars 2014 17:02:06 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * HorairesId generated by hbm2java
 */
@Embeddable
public class HorairesId implements java.io.Serializable {

	private int idcat;
	private int idcal;

	public HorairesId() {
	}

	public HorairesId(int idcat, int idcal) {
		this.idcat = idcat;
		this.idcal = idcal;
	}

	@Column(name = "idcat", nullable = false)
	public int getIdcat() {
		return this.idcat;
	}

	public void setIdcat(int idcat) {
		this.idcat = idcat;
	}

	@Column(name = "idcal", nullable = false)
	public int getIdcal() {
		return this.idcal;
	}

	public void setIdcal(int idcal) {
		this.idcal = idcal;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HorairesId))
			return false;
		HorairesId castOther = (HorairesId) other;

		return (this.getIdcat() == castOther.getIdcat())
				&& (this.getIdcal() == castOther.getIdcal());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdcat();
		result = 37 * result + this.getIdcal();
		return result;
	}

}
