package org.bio.model;

// Generated 19 mars 2014 17:02:06 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Synthese generated by hbm2java
 */
@Entity
@Table(name = "synthese")
public class Synthese implements java.io.Serializable {

	private SyntheseId id;
	private Personnel personnel;
	private Date e1;
	private Date s1;
	private Date e2;
	private Date s2;
	private Boolean absent;
	private Boolean conge;
	private Date presenceHrMn;
	private Date retardHrMn;
	private Date hsupHrMn;
	private Boolean ferie;
	private Byte autorisation;

	public Synthese() {
	}

	public Synthese(SyntheseId id, Personnel personnel) {
		this.id = id;
		this.personnel = personnel;
	}

	public Synthese(SyntheseId id, Personnel personnel, Date e1, Date s1,
			Date e2, Date s2, Boolean absent, Boolean conge, Date presenceHrMn,
			Date retardHrMn, Date hsupHrMn, Boolean ferie, Byte autorisation) {
		this.id = id;
		this.personnel = personnel;
		this.e1 = e1;
		this.s1 = s1;
		this.e2 = e2;
		this.s2 = s2;
		this.absent = absent;
		this.conge = conge;
		this.presenceHrMn = presenceHrMn;
		this.retardHrMn = retardHrMn;
		this.hsupHrMn = hsupHrMn;
		this.ferie = ferie;
		this.autorisation = autorisation;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "jour", column = @Column(name = "jour", nullable = false, length = 10)),
			@AttributeOverride(name = "idper", column = @Column(name = "idper", nullable = false)) })
	public SyntheseId getId() {
		return this.id;
	}

	public void setId(SyntheseId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idper", nullable = false, insertable = false, updatable = false)
	public Personnel getPersonnel() {
		return this.personnel;
	}

	public void setPersonnel(Personnel personnel) {
		this.personnel = personnel;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "e1", length = 8)
	public Date getE1() {
		return this.e1;
	}

	public void setE1(Date e1) {
		this.e1 = e1;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "s1", length = 8)
	public Date getS1() {
		return this.s1;
	}

	public void setS1(Date s1) {
		this.s1 = s1;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "e2", length = 8)
	public Date getE2() {
		return this.e2;
	}

	public void setE2(Date e2) {
		this.e2 = e2;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "s2", length = 8)
	public Date getS2() {
		return this.s2;
	}

	public void setS2(Date s2) {
		this.s2 = s2;
	}

	@Column(name = "absent")
	public Boolean getAbsent() {
		return this.absent;
	}

	public void setAbsent(Boolean absent) {
		this.absent = absent;
	}

	@Column(name = "conge")
	public Boolean getConge() {
		return this.conge;
	}

	public void setConge(Boolean conge) {
		this.conge = conge;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "presenceHrMn", length = 8)
	public Date getPresenceHrMn() {
		return this.presenceHrMn;
	}

	public void setPresenceHrMn(Date presenceHrMn) {
		this.presenceHrMn = presenceHrMn;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "retardHrMn", length = 8)
	public Date getRetardHrMn() {
		return this.retardHrMn;
	}

	public void setRetardHrMn(Date retardHrMn) {
		this.retardHrMn = retardHrMn;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hSupHrMn", length = 8)
	public Date getHsupHrMn() {
		return this.hsupHrMn;
	}

	public void setHsupHrMn(Date hsupHrMn) {
		this.hsupHrMn = hsupHrMn;
	}

	@Column(name = "ferie")
	public Boolean getFerie() {
		return this.ferie;
	}

	public void setFerie(Boolean ferie) {
		this.ferie = ferie;
	}

	@Column(name = "autorisation")
	public Byte getAutorisation() {
		return this.autorisation;
	}

	public void setAutorisation(Byte autorisation) {
		this.autorisation = autorisation;
	}

}
