package org.bio.model;

// Generated 19 mars 2014 17:02:06 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * GlobalHistorique generated by hbm2java
 */
@Entity
@Table(name = "global_historique")
public class GlobalHistorique implements java.io.Serializable {

	private Date jour;
	private int idfer;
	private int idcal;
	private Ferie ferie;
	private Calendrier calendrier;

	public GlobalHistorique() {
	}
	

	public GlobalHistorique(Date jour, Ferie ferie,
			Calendrier calendrier) {
		this.jour = jour;
		this.ferie = ferie;
		this.calendrier = calendrier;
	}
	@Id
	@Column(name = "jour", unique = true, nullable = false, length = 10)
	public Date getJour() {
		return this.jour;
	}

	public void setJour(Date jour) {
		this.jour = jour;
	}

	@Column(name = "idfer", nullable = true)
	public int getIdfer() {
		return this.idfer;
	}

	public void setIdfer(int idfer) {
		this.idfer = idfer;
	}

	@Column(name = "idcal", nullable = true)
	public int getIdcal() {
		return this.idcal;
	}

	public void setIdcal(int idcal) {
		this.idcal = idcal;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idfer", nullable = true, insertable = false, updatable = false)
	public Ferie getFerie() {
		return this.ferie;
	}

	public void setFerie(Ferie ferie) {
		this.ferie = ferie;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcal", nullable = true, insertable = false, updatable = false)
	public Calendrier getCalendrier() {
		return this.calendrier;
	}

	public void setCalendrier(Calendrier calendrier) {
		this.calendrier = calendrier;
	}
	
	

}
