package org.bio.model;

// Generated 26 mars 2014 09:34:58 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OperateurRolesId generated by hbm2java
 */
@Embeddable
public class OperateurRolesId implements java.io.Serializable {

	private int idop;
	private int idrol;

	public OperateurRolesId() {
	}

	public OperateurRolesId(int idop, int idrol) {
		this.idop = idop;
		this.idrol = idrol;
	}

	@Column(name = "idop", nullable = false)
	public int getIdop() {
		return this.idop;
	}

	public void setIdop(int idop) {
		this.idop = idop;
	}

	@Column(name = "idrol", nullable = false)
	public int getIdrol() {
		return this.idrol;
	}

	public void setIdrol(int idrol) {
		this.idrol = idrol;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OperateurRolesId))
			return false;
		OperateurRolesId castOther = (OperateurRolesId) other;

		return (this.getIdop() == castOther.getIdop())
				&& (this.getIdrol() == castOther.getIdrol());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdop();
		result = 37 * result + this.getIdrol();
		return result;
	}

}
